---

name: Docker tests

"on":
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - "grpc/clients/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: tmp/proto:latest
