---

name: Javascript tests

"on":
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - "grpc/clients/cpp/**"
      - "grpc/clients/go/**"
      - "grpc/clients/java/**"
      # do not ignore grpc/clients/js/
      - "grpc/clients/python/**"
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - "grpc/clients/cpp/**"
      - "grpc/clients/go/**"
      - "grpc/clients/java/**"
      # do not ignore grpc/clients/js/
      - "grpc/clients/python/**"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          cd grpc/clients/js
          npm ci

      - name: Lint
        run: |
          cd grpc/clients/js
          npm run lint

      - name: Test
        env:
          CI: true
          GRPC_NODE: ${{ secrets.GRPC_NODE }}
          WALLETSERVER: ${{ secrets.WALLETSERVER }}
        run: |
          cd grpc/clients/js
          npm test
