name: Javascript tests

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - "cpp/**"
      - "python/**"
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - "cpp/**"
      - "python/**"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        cd js
        npm ci

    - name: Test
      env:
        GRPC_NODE: ${{ secrets.GRPC_NODE }}
        WALLETSERVER: ${{ secrets.WALLETSERVER }}
      run: |
        cd js
        npm test
      env:
        CI: true
